# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: user-agent
type: Opaque
data:
  API_KEY_AUTHORIZED: "${AGENT_API_KEY}"
---

# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: agent-cert
  namespace: user-agent
type: Opaque
data:
  tls.key: |
    ${AGENT_TLS_KEY}
  tls.crt: |
    ${AGENT_TLS_CRT}
---

