# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-pvc
  namespace: user-agent
  labels:
    app: agent-pvc
spec:
  storageClassName: nfs-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---

