apiVersion: v1
kind: Secret
metadata:
  name: provider-catalogue-credentials
  namespace: provider-catalogue
type: Opaque
data:
  PARTICIPANT_AGENT_SECRET_KEY: ${AGENT_API_KEY}
  API_KEY_AUTHORIZED: ${PROVIDER_CATALOGUE_API_KEY}
---
