apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphdb-prov-catalogue-data-pvc
  namespace: provider-catalogue
  labels:
    app: graphdb-prov-catalogue-data-pvc
spec:
  storageClassName: nfs-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

