apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ces-postgres-data
  namespace: ces
spec:
  storageClassName: nfs-storageclass
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---

