apiVersion: v1
kind: Secret
metadata:
  name: ces-postgres-secret
  namespace: ces
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: ${CES_POSTGRES_USER}
  POSTGRES_PASSWORD: ${CES_POSTGRES_PASSWORD}
---
