# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: issuer-cert
  namespace: vc-issuer
type: Opaque
data:
  tls.key: |
    ${ISSUER_TLS_KEY}
  tls.crt: |
    ${ISSUER_TLS_CRT}
---
