apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphdb-data-pvc
  namespace: federated-catalogue
  labels:
    app: graphdb-data-pvc
spec:
  storageClassName: nfs-storageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

